description = "指定されたディレクトリ内のANA Pay利用履歴画像からCSVを生成します。 使い方: /anapay_csv -i <入力ディレクトリ名> -o <出力ファイル名>"
prompt = """
以下の指示に従って、画像ファイルから取引履歴を抽出し、単一のCSVファイルとして出力してください。

---

### 1. 処理対象の画像ファイル

以下のファイルを `read_file` ツールを使用して処理してください。
!{ls -1 <入力ディレクトリ名>/*.jpg | sed 's/^/- /'}

### 2. 出力CSVの仕様

**ヘッダー:**
`"計算対象","日付","内容","金額（円）","保有金融機関","大項目","中項目","メモ","振替","ID"`

**各列のルール:**
- **計算対象:** 常に `"1"`
- **日付:** `年/月/日` 形式 (例: `2025/07/31`)。時刻は含めないでください。
- **内容:** 画像から読み取った利用内容を記載してください。
- **金額（円）:** カンマを含まない数値 (例: `-2000`)。チャージはプラス、支払いはマイナスで表現してください。
- **保有金融機関:** 常に `"ANA Pay"`
- **大項目:** 常に `"未分類"`
- **中項目:** 常に `"未分類"`
- **メモ:** 常に空欄にしてください。
- **振替:** 常に `"0"`
- **ID:** 常に空欄にしてください。

### 3. 最終的な出力

- 上記の全画像ファイルの処理結果を、単一のCSVデータに統合してください。
- 統合したデータを、**日付の昇順**でソートしたものを最終的な出力としてください。
- <出力ファイル名>というファイルを作成し、CSVデータを書き込んでください。

---
"""